status = [
  "build (lts/*, false)",
  "test (lts/*, false)",
  "license",
  "pr-apk-no-deploy",
  "pr-ios-no-deploy",
#  "DCO",
]
block_labels = [ "S-do-not-merge-yet" ]
update_base_for_deletes = true
cut_body_after = "<details>"
#timeout_sec = 36000 # ten hours
