packages:
  - api
  - app
  - web
  - library/data-model
  - library/forms
  - library/instrumentation
  - load-testing/shared
  - load-testing/coordinator
  - load-testing/agents
  - load-testing/infra
  - infrastructure/aws-cdk
onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - appium
  - appium-ios-tuntap
  - aws-sdk
  - chromedriver
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - leveldown
  - msw
  - protobufjs
  - sharp
