packages:
  - api
  - app
  - web
  - library/data-model
  - library/forms
  - library/themes/theme-base
  - library/themes/theme-default
  - library/themes/theme-fieldmark
  - library/themes/theme-bss
  - library/themes/theme-registry
  - infrastructure/aws-cdk
  - e2e
onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - appium
  - appium-ios-tuntap
  - aws-sdk
  - chromedriver
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - leveldown
  - msw
  - protobufjs
  - sharp
