packages:
  - api
  - app
  - web
  - library/data-model
  - library/forms
  - infrastructure/aws-cdk
  - e2e
onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - appium
  - appium-ios-tuntap
  - aws-sdk
  - chromedriver
  - edgedriver
  - es5-ext
  - esbuild
  - geckodriver
  - leveldown
  - msw
  - protobufjs
  - sharp

minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: 'no-downgrade'
strictDepBuilds: true
ignoreScripts: true

overrides:
  'level': '^7.0.0'
  'sharp': '^0.34.2'

peerDependencyRules:
  allowedVersions:
    '@tanstack/zod-adapter>zod': '4'

trustPolicyExclude:
  - '@wdio/logger@9.18.0'
  - 'chokidar@4.0.3'
  - '@wdio/repl@9.16.2'
  - 'semver'
  - 'undici-types@6.21.0'
