# File: .github/actions/faims-config/action.yml
name: "FAIMS Config"
description: "Pull FAIMS configuration into CDK context and output AWS details. Requires an already cloned github repo!"
inputs:
  environment:
    description: "The deployment environment (e.g., dev, staging, production)"
    required: true
  config-repo-path:
    description: "Path to the cloned config repository relative to the GitHub workspace"
    required: true
  branch:
    description: "Branch to use in the config repository"
    required: true
    default: "main"
outputs:
  aws-region:
    description: "AWS region from the config"
  aws-account:
    description: "AWS account ID from the config"
runs:
  using: "composite"
  steps:
    - name: Run config script
      shell: bash
      run: |
        cd infrastructure/aws-cdk
        chmod +x config.sh
        ./config.sh pull ${{ inputs.environment }} --repo-path ../../${{ inputs.config-repo-path }} --branch ${{ inputs.branch }}

    - name: Parse config and set outputs
      shell: bash
      run: |
        CONFIG_FILE="infrastructure/aws-cdk/configs/${{ inputs.environment }}.json"
        if [ ! -f "$CONFIG_FILE" ]; then
          echo "Error: Config file not found at $CONFIG_FILE"
          exit 1
        fi

        AWS_REGION=$(jq -r '.aws.region' "$CONFIG_FILE")
        AWS_ACCOUNT=$(jq -r '.aws.account' "$CONFIG_FILE")

        echo "aws-region=$AWS_REGION" >> $GITHUB_OUTPUT
        echo "aws-account=$AWS_ACCOUNT" >> $GITHUB_OUTPUT

        echo "AWS Region: $AWS_REGION"
        echo "AWS Account: $AWS_ACCOUNT"
