// Copyright 2023 FAIMS Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import {FieldType} from './state/initial';

const fields: {[key: string]: FieldType} = {
  FAIMSTextField: {
    'component-namespace': 'faims-custom',
    'component-name': 'FAIMSTextField',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'FAIMS Text Field',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'FAIMS Text Field',
    humanReadableDescription: 'Single-line text input for free-form entries',
    category: 'Text',
    showInChooser: true,
    order: 1,
  },

  DateTimePicker: {
    'component-namespace': 'faims-custom',
    'component-name': 'DateTimePicker',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Date time picker',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Date time picker',
    humanReadableDescription: 'Select a calendar date and precise time',
    category: 'Date & Time',
    showInChooser: true,
    order: 2,
  },

  DatePicker: {
    'component-namespace': 'faims-custom',
    'component-name': 'DatePicker',
    'type-returned': 'faims-core::Date',
    'component-parameters': {
      label: 'Date picker',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Date picker',
    humanReadableDescription: 'Choose a calendar date (no time)',
    category: 'Date & Time',
    showInChooser: true,
    order: 3,
  },

  MonthPicker: {
    'component-namespace': 'faims-custom',
    'component-name': 'MonthPicker',
    'type-returned': 'faims-core::Date',
    'component-parameters': {
      label: 'Month picker',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Month picker',
    humanReadableDescription: 'Pick a month and year only',
    category: 'Date & Time',
    showInChooser: true,
    order: 4,
  },

  DateTimeNow: {
    'component-namespace': 'faims-custom',
    'component-name': 'DateTimeNow',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Date and Time with Now button',
      fullWidth: true,
      helperText: '',
      variant: 'outlined',
      required: false,
      is_auto_pick: false,
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Date and Time with Now button',
    humanReadableDescription: 'Date-time input with “Now” quick-fill',
    category: 'Date & Time',
    showInChooser: true,
    order: 5,
  },

  Email: {
    'component-namespace': 'formik-material-ui',
    'component-name': 'TextField',
    'type-returned': 'faims-core::Email',
    'component-parameters': {
      label: 'Email',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
      InputProps: {
        type: 'email',
      },
    },
    validationSchema: [['yup.string'], ['yup.email', 'Enter a valid email']],
    initialValue: '',
    humanReadableName: 'Email',
    humanReadableDescription: 'Validates and captures an e-mail address',
    category: 'Text',
    showInChooser: true,
    order: 6,
  },

  Number: {
    'component-namespace': 'formik-material-ui',
    'component-name': 'TextField',
    'type-returned': 'faims-core::Integer',
    'component-parameters': {
      label: 'Number field',
      fullWidth: true,
      helperText: '',
      variant: 'outlined',
      required: false,
      InputProps: {
        type: 'number',
      },
    },
    validationSchema: [['yup.number']],
    initialValue: '',
    humanReadableName: 'Number field',
    humanReadableDescription: 'Plain numeric input without limits',
    category: 'Numbers',
    showInChooser: true,
    order: 7,
  },

  ControlledNumber: {
    'component-namespace': 'formik-material-ui',
    'component-name': 'TextField',
    'type-returned': 'faims-core::Integer',
    'component-parameters': {
      label: 'Controlled number',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
      InputProps: {
        type: 'number',
      },
    },
    validationSchema: [
      ['yup.number'],
      ['yup.min', 10, 'Must be 10 or more'],
      ['yup.max', 20, 'Must be 20 or less'],
    ],
    initialValue: '',
    humanReadableName: 'Controlled number',
    humanReadableDescription: 'Numeric input with min/max validation',
    category: 'Numbers',
    showInChooser: true,
    order: 8,
  },

  BasicAutoIncrementer: {
    'component-namespace': 'faims-custom',
    'component-name': 'BasicAutoIncrementer',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      name: 'basic-autoincrementer-field',
      id: 'basic-autoincrementer-field',
      variant: 'outlined',
      required: true,
      num_digits: 5,
      form_id: 'default',
      label: 'Auto Incrementing Field',
    },
    validationSchema: [['yup.string'], ['yup.required']],
    initialValue: '',
    humanReadableName: 'Auto Incrementing Field',
    humanReadableDescription: 'Generates sequential IDs automatically',
    category: 'Numbers',
    showInChooser: true,
    order: 9,
  },

  MultipleTextField: {
    'component-namespace': 'formik-material-ui',
    'component-name': 'MultipleTextField',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Text Field',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
      multiline: true,
      InputProps: {
        type: 'text',
        rows: 4,
      },
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Text Field',
    humanReadableDescription: 'Multi-line text area for longer notes',
    category: 'Text',
    showInChooser: true,
    order: 10,
  },

  Checkbox: {
    'component-namespace': 'faims-custom',
    'component-name': 'Checkbox',
    'type-returned': 'faims-core::Bool',
    'component-parameters': {
      label: 'Checkbox',
      name: 'checkbox-field',
      id: 'checkbox-field',
      required: false,
      type: 'checkbox',
      helperText: '',
      advancedHelperText: '',
    },
    validationSchema: [['yup.bool']],
    initialValue: false,
    humanReadableName: 'Checkbox',
    humanReadableDescription: 'Boolean yes/no toggle box',
    category: 'Choice',
    showInChooser: true,
    order: 11,
  },

  FileUploader: {
    'component-namespace': 'faims-custom',
    'component-name': 'FileUploader',
    'type-returned': 'faims-attachment::Files',
    'component-parameters': {
      label: 'Upload a File',
      name: 'file-upload-field',
      id: 'file-upload-field',
      helperText: '',
    },
    validationSchema: [['yup.mixed']],
    initialValue: null,
    humanReadableName: 'Upload a File',
    humanReadableDescription: 'Attach one or more files to the record',
    category: 'Media',
    showInChooser: true,
    order: 12,
  },

  MapFormField: {
    'component-namespace': 'mapping-plugin',
    'component-name': 'MapFormField',
    'type-returned': 'faims-core::JSON',
    'component-parameters': {
      name: 'map-form-field',
      id: 'map-form-field',
      variant: 'outlined',
      required: false,
      featureType: 'Point',
      zoom: 12,
      label: 'Select a Point',
      geoTiff: '',
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Select a Point',
    humanReadableDescription: 'Interactive map for selecting a point',
    category: 'Location',
    showInChooser: true,
    order: 13,
  },

  MultiSelect: {
    'component-namespace': 'faims-custom',
    'component-name': 'MultiSelect',
    'type-returned': 'faims-core::Array',
    'component-parameters': {
      label: 'Select Multiple',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
      select: true,
      SelectProps: {
        multiple: true,
      },
      ElementProps: {
        expandedChecklist: false,
        options: [
          {value: 'Default', label: 'Default'},
          {value: 'Default2', label: 'Default2'},
        ],
      },
    },
    validationSchema: [['yup.array']],
    initialValue: [],
    humanReadableName: 'Select Multiple',
    humanReadableDescription: 'Pick several options from a list',
    category: 'Choice',
    showInChooser: true,
    order: 14,
  },

  RadioGroup: {
    'component-namespace': 'faims-custom',
    'component-name': 'RadioGroup',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Select one option',
      name: 'radio-group-field',
      id: 'radio-group-field',
      advancedHelperText: '',
      variant: 'outlined',
      required: false,
      ElementProps: {
        options: [
          {value: '1', label: '1', RadioProps: {id: 'radio-group-field-1'}},
        ],
      },
      helperText: '',
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Select one option',
    humanReadableDescription: 'Single-choice radio button set',
    category: 'Choice',
    showInChooser: true,
    order: 15,
  },

  RandomStyle: {
    'component-namespace': 'faims-custom',
    'component-name': 'RandomStyle',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      fullWidth: true,
      helperText: '',
      variant: 'outlined',
      label: 'Title',
      variant_style: 'h5',
      html_tag: '',
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Title',
    humanReadableDescription: 'Stylised heading or HTML content',
    category: 'Display',
    showInChooser: true,
    order: 16,
  },

  RichText: {
    'component-namespace': 'faims-custom',
    'component-name': 'RichText',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Unused',
      content: 'Hello __World__',
    },
    humanReadableName: 'RichText',
    humanReadableDescription: 'Rich-text editor with Markdown support',
    category: 'Display',
    showInChooser: true,
    order: 17,
  },

  RelatedRecordSelector: {
    'component-namespace': 'faims-custom',
    'component-name': 'RelatedRecordSelector',
    'type-returned': 'faims-core::Relationship',
    'component-parameters': {
      label: 'Select Related',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      required: true,
      related_type: '',
      relation_type: 'faims-core::Child',
      multiple: false,
      allowLinkToExisting: true,
    },
    validationSchema: [['yup.string']],
    humanReadableName: 'Select Related',
    humanReadableDescription: 'Link this record to another existing one',
    category: 'Relationship',
    showInChooser: true,
    order: 18,
  },

  Select: {
    'component-namespace': 'faims-custom',
    'component-name': 'Select',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Select Field',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      required: false,
      ElementProps: {options: []},
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Select Field',
    humanReadableDescription: 'Dropdown list allowing one selection',
    category: 'Choice',
    showInChooser: true,
    order: 19,
  },

  AdvancedSelect: {
    'component-namespace': 'faims-custom',
    'component-name': 'AdvancedSelect',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Select Field',
      fullWidth: true,
      helperText: '',
      required: false,
      ElementProps: {
        optiontree: [{name: 'Default', children: []}],
      },
      valuetype: 'full',
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Select Field (Hierarchical)',
    humanReadableDescription: 'Hierarchical dropdown supporting nested options',
    category: 'Choice',
    showInChooser: true,
    order: 20,
  },

  TakePhoto: {
    'component-namespace': 'faims-custom',
    'component-name': 'TakePhoto',
    'type-returned': 'faims-attachment::Files',
    'component-parameters': {
      name: 'take-photo-field',
      helperText: '',
      advancedHelperText: '',
      label: 'Take Photo',
    },
    validationSchema: [
      ['yup.array'],
      ['yup.of', [['yup.object'], ['yup.nullable']]],
      ['yup.nullable'],
    ],
    initialValue: null,
    humanReadableName: 'Take Photo',
    humanReadableDescription: 'Capture and attach an image via camera',
    category: 'Media',
    showInChooser: true,
    order: 21,
  },

  TakePoint: {
    'component-namespace': 'faims-custom',
    'component-name': 'TakePoint',
    'type-returned': 'faims-pos::Location',
    'component-parameters': {
      name: 'take-point-field',
      helperText: '',
      label: 'Take point',
    },
    validationSchema: [['yup.object'], ['yup.nullable']],
    initialValue: null,
    humanReadableName: 'Take point',
    humanReadableDescription: 'Record GPS location coordinates',
    category: 'Location',
    showInChooser: true,
    order: 22,
  },

  TemplatedStringField: {
    'component-namespace': 'faims-custom',
    'component-name': 'TemplatedStringField',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Templated String Field',
      fullWidth: true,
      name: 'templated-field',
      helperText: '',
      required: true,
      template: ' {{}}',
      hidden: true,
    },
    validationSchema: [['yup.string'], ['yup.required']],
    initialValue: '',
    humanReadableName: 'Templated String Field',
    humanReadableDescription: 'Auto-generates text from a template',
    category: 'Text',
    showInChooser: true,
    order: 23,
  },

  QRCodeFormField: {
    'component-namespace': 'qrcode',
    'component-name': 'QRCodeFormField',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      name: 'qr-code-field',
      required: false,
      label: 'Scan QR Code',
      helperText: '',
    },
    validationSchema: [['yup.string']],
    initialValue: '',
    humanReadableName: 'Scan QR Code',
    humanReadableDescription: 'Scan and store a QR-code value',
    category: 'Text',
    showInChooser: true,
    order: 24,
  },

  AddressField: {
    'component-namespace': 'faims-custom',
    'component-name': 'AddressField',
    'type-returned': 'faims-core::JSON',
    'component-parameters': {
      helperText: '',
      required: false,
      name: 'Address',
      label: 'Address',
    },
    validationSchema: [['yup.object'], ['yup.nullable']],
    humanReadableName: 'Address',
    humanReadableDescription: 'Structured street address input',
    category: 'Text',
    showInChooser: true,
    order: 25,
  },

  NumberField: {
    'component-namespace': 'faims-custom',
    'component-name': 'NumberField',
    'type-returned': 'faims-core::Number',
    'component-parameters': {
      label: 'Number Input',
      fullWidth: true,
      helperText: '',
      advancedHelperText: '',
      required: false,
      InputProps: {
        type: 'number',
      },
    },
    validationSchema: [['yup.number'], ['yup.nullable']],
    initialValue: null,
    humanReadableName: 'Number Input',
    humanReadableDescription: 'Floating-point number entry field',
    category: 'Numbers',
    showInChooser: true,
    order: 26,
  },
};

export const getFieldNames = () => {
  return Object.keys(fields);
};

// Return a copy of the spec for this field type
export const getFieldSpec = (fieldType: string) => {
  return JSON.parse(JSON.stringify(fields[fieldType])) as FieldType;
};
