update_fastlane

default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
APPLE_BUNDLE_IDENTIFIER = ENV["APPLE_BUNDLE_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]
BROWSERSTACK_USERNAME = ENV["BROWSERSTACK_USERNAME"]
BROWSERSTACK_ACCESS_KEY = ENV["BROWSERSTACK_ACCESS_KEY"]


# keychain details are hard-coded here with a generated password
KEYCHAIN_NAME = "keychain"
KEYCHAIN_PASSWORD = SecureRandom.hex(32) 

def delete_temp_keychain()
  delete_keychain(
    name: KEYCHAIN_NAME
  ) if File.exist? File.expand_path("~/Library/Keychains/#{KEYCHAIN_NAME}-db")
end

def ensure_temp_keychain()
  delete_temp_keychain()
  create_keychain(
    name: KEYCHAIN_NAME,
    password: KEYCHAIN_PASSWORD,
    unlock: false,
    timeout: 0
  )
end

platform :ios do
 
  lane :closed_beta_browserstack do
    ensure_temp_keychain()

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    cocoapods(
      clean_install: true
    )

    match(
      type: 'development',
      storage_mode: "git",
      app_identifier: "#{APPLE_BUNDLE_IDENTIFIER}",
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: false,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
      api_key: api_key
    )

    gym(
      configuration: "Debug",
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => "match Development #{APPLE_BUNDLE_IDENTIFIER}"
        },
        teamID: ENV["APP_STORE_CONNECT_TEAM_ID"]
      }
    )

    upload_to_browserstack_app_automate(
      browserstack_username: "#{BROWSERSTACK_USERNAME}",
      browserstack_access_key: "#{BROWSERSTACK_ACCESS_KEY}",
      custom_id: "ios-github-actions-fastlane"
    )

    delete_temp_keychain()
  end


  lane :closed_beta_testflight do
    ensure_temp_keychain()

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    #increment_build_number(xcodeproj: "App.xcodeproj")
    #handled by script and xcode in build phases, I hope.

    cocoapods(
      clean_install: true
    )

    # debugging - get our profile info
    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )
    
    profiles = get_provisioning_profile(
      app_identifier: "Match AppStore #{APPLE_BUNDLE_IDENTIFIER}",
      api_key: api_key,
      readonly: true
    )
    
    puts "Profile information: #{profiles}"


    match(
      type: 'appstore',
      storage_mode: "git",
      app_identifier: "#{APPLE_BUNDLE_IDENTIFIER}",
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: false,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
      api_key: api_key
    )

    gym(
      configuration: "Release", #make sure this key matches xcode signing and capabilities.
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => "match AppStore #{APPLE_BUNDLE_IDENTIFIER}"
        },
        teamID: ENV["APP_STORE_CONNECT_TEAM_ID"]
      }
    )
    changelog = changelog_from_git_commits(
      match_lightweight_tag: false,
      merge_commit_filtering: "exclude_merges"
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{APPLE_BUNDLE_IDENTIFIER}",
      skip_waiting_for_build_processing: false,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "App.ipa",
      changelog: changelog
    )

    delete_temp_keychain()
  end

  lane :production do
    ensure_temp_keychain()

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    #increment_build_number(xcodeproj: "App.xcodeproj")
    #handled by script and xcode in build phases, I hope.

    cocoapods(
      clean_install: true
    )

    match(
      type: 'appstore',
      storage_mode: "git",
      app_identifier: "#{APPLE_BUNDLE_IDENTIFIER}",
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: false,
      keychain_name: KEYCHAIN_NAME,
      keychain_password: KEYCHAIN_PASSWORD,
      api_key: api_key
    )

    gym(
      configuration: "Release", #make sure this key matches xcode signing and capabilities.
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            DEVELOPER_APP_ID => "match AppStore #{APPLE_BUNDLE_IDENTIFIER}"
        },
        teamID: ENV["APP_STORE_CONNECT_TEAM_ID"]
      }
    )

    deliver(
      app_identifier: "#{APPLE_BUNDLE_IDENTIFIER}",
      ipa: "App.ipa",
      submit_for_review: false,
      automatic_release: false,
      force: true,
      run_precheck_before_submit: false
    )

    delete_temp_keychain()
  end
end
