services:
  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=48h'
      - '--web.enable-remote-write-receiver'

  pushgateway:
    image: prom/pushgateway:v1.10.0
    ports:
      - '${PUSHGATEWAY_PORT:-9091}:9091'

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - '${GRAFANA_PORT:-3030}:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./observability/grafana/dashboards/json:/etc/grafana/provisioning/dashboards/json:ro

  couchdb-exporter:
    image: gesellix/couchdb-prometheus-exporter:${COUCHDB_EXPORTER_VERSION:-latest}
    ports:
      - '${COUCHDB_EXPORTER_PORT:-9984}:9984'
    env_file:
      - couchdb-exporter.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
