/*
 * Copyright 2021 Macquarie University
 *
 * Licensed under the Apache License Version 2.0 (the, "License");
 * you may not use, this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND either express or implied.
 * See, the License, for the specific language governing permissions and
 * limitations under the License.
 *
 * Filename: IOSTest.java
 * Description:
 *   TODO
 */

package org.fedarch.faims3.ios;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;



import org.fedarch.faims3.AstroSky;
import org.fedarch.faims3.E2ETest;
import org.fedarch.faims3.TestUtils;
import org.json.JSONException;
import org.json.JSONObject;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.appium.java_client.MobileBy;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.nativekey.AndroidKey;
import io.appium.java_client.android.nativekey.KeyEvent;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.ios.IOSElement;
import io.appium.java_client.remote.IOSMobileCapabilityType;
import io.appium.java_client.touch.offset.PointOption;

public class IOSTest implements E2ETest {
	protected static IOSDriver<IOSElement> driver;

	private static boolean isLocal;

	// Save latitude generated by GPS button for the JSON check later
	protected String latitude;

	// Save long generated by GPS button for the JSON check later
	protected String longitude;

	// Newly created observation form's id
	protected String recordUuid;

	public IOSTest() {
		setDatabase();
	}

	/**
	 * Setup the IOSDriver based on parameter.
	 * @param localTest If true, then we'll set up a local connection. Otherwise we'll set up a browserstack one.
	 * @param testDesc Test description for browserstack
	 * @return an IOSDriver instance
	 * @throws MalformedURLException
	 */
	public static void setup(boolean localTest, String testDesc) throws MalformedURLException {
		DesiredCapabilities caps = new DesiredCapabilities();
		// allow location services
	    caps.setCapability(IOSMobileCapabilityType.LOCATION_SERVICES_ENABLED, "true");
	    caps.setCapability(IOSMobileCapabilityType.LOCATION_SERVICES_AUTHORIZED, "true");
	    // accept location pop ups
	    caps.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, "true");
	    caps.setCapability("automationName", "XCUITest");
		if (localTest) {
			localConnectionSetup(caps);
			isLocal = true;
		} else {
		    browserstackSetup(caps, testDesc);
		    isLocal = false;
		}
		// this is required because the autoAcceptAlerts doesn't actually work..
		// see https://github.com/appium/appium/issues/14741
		driver.setSetting("acceptAlertButtonSelector", "**/XCUIElementTypeButton[`label == 'Allow While Using App'`]");
	}

	/**
	 * Localhost setup for Rini's machine.
	 * @throws MalformedURLException
	 */
	public static void localConnectionSetup(DesiredCapabilities caps) throws MalformedURLException {
	    caps.setCapability("automationName", "XCUITest");
		caps.setCapability("platformName", "iOS");
	    caps.setCapability("platformVersion", "13.7");
	    caps.setCapability("deviceName", "iPhone 11");
	    caps.setCapability("adbExecTimeout", "1200000");
	    caps.setCapability("app", "/Users/riniangreani/Documents/Payload/App.app");
	    driver = new IOSDriver<IOSElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	}

	/**
	 * Browserstack setup for the test
	 * @param testDescription Test scenario. Link to JIRA if possible.
	 * @throws MalformedURLException
	 */
	public static void browserstackSetup(DesiredCapabilities caps, String testDescription) throws MalformedURLException {
	    caps.setCapability("project", "FAIMS3 - iOS Tests");
	    caps.setCapability("build", "Alpha");
	    caps.setCapability("name", testDescription.concat(" : ").concat(TestUtils.getCommitMessage()));

	    // Specify device and os_version for testing
	    caps.setCapability("device", "iPhone 12");
        caps.setCapability("os_version", "12");
	    // Latest Appium browserstack version with correct geolocation
	    caps.setCapability("browserstack.appium_version", "1.21.0");

	    turnOnBrowserstackLogs(caps);

	    caps.setCapability("app", System.getenv("app_url"));
	    caps.setCapability("browserstack.user", System.getenv("BROWSERSTACK_USERNAME"));
	    caps.setCapability("browserstack.key", System.getenv("BROWSERSTACK_ACCESS_KEY"));

	    driver = new IOSDriver<IOSElement>(
                new URL("http://hub-cloud.browserstack.com/wd/hub"), caps);

	}

	/**
	 * Optional logging options for browserstack
	 * @param caps
	 * @return
	 */
	public static void turnOnBrowserstackLogs(DesiredCapabilities caps) {
	    // Log settings to debug
	    caps.setCapability("browserstack.console", "verbose");
	    HashMap networkLogsOptions = new HashMap<>();
	    networkLogsOptions.put("captureContent", Boolean.TRUE);
	    // turn on network logs
	    caps.setCapability("browserstack.networkLogs", "true");
	    caps.setCapability("browserstack.networkLogsOptions", networkLogsOptions);
	}

	/**
	 * True if this is connected to Browserstack.
	 * @return
	 */
	@Override
	public boolean isUsingBrowserstack() {
		return !isLocal;
	}

	/**
	 * Fill out all fields in test AsTRoSkY form with valid values.
	 */
	@Override
	public void fillOutFormWithValidFields() {
		WebDriverWait wait = new WebDriverWait(driver, 10);
		// Test GPS point
		WebElement gpsPoint = wait.until(
		        ExpectedConditions.presenceOfElementLocated(
		        		MobileBy.AccessibilityId("TAKE POINT")));
		gpsPoint.click();
		// Wait for the location pop up to disappear
		wait.until(
		        ExpectedConditions.presenceOfElementLocated(
		        		MobileBy.AccessibilityId("TAKE POINT")));
		
		// Make sure the point text has been updated
		wait.until(
		        ExpectedConditions.invisibilityOfElementLocated(
		        		MobileBy.iOSClassChain("**/XCUIElementTypeStaticText[`label == \"No point taken.\"`]")));
		// now check that the point was captured
		validateLatLong();

		// Click on Action button
	    // The value will be updated in JSON
		WebElement action = driver.findElement(MobileBy.AccessibilityId("ACTION!"));
		action.click();

	    // Email field
	    WebElement emailField = driver.findElement(
	    		MobileBy.xpath("//XCUIElementTypeOther[@name=\"Email Address\"]/following-sibling::XCUIElementTypeTextField"));
	    emailField.sendKeys(AstroSky.EMAIL_IOS);

	    TestUtils.scrollDown(driver);

	    // Colour field
	    IOSElement strField = driver.findElement(
	    		MobileBy.xpath("//XCUIElementTypeOther[@name=\"Favourite Colour\"]/following-sibling::XCUIElementTypeTextField"));
	    // clear old value
	    strField.clear();
	    strField.setValue(AstroSky.COLOUR);

	    // Text area - test unicode
	    IOSElement textField = driver.findElement(
	    		MobileBy.xpath("//XCUIElementTypeOther[@name=\"Textarea Field Label\"]/following-sibling::XCUIElementTypeTextView"));
	    textField.clear();
	    textField.setValue(AstroSky.UNICODE);

	    TestUtils.scrollDown(driver);

	    WebElement intField = driver.findElement(
	    		MobileBy.xpath("//XCUIElementTypeOther[@name= \"Integer Field Label\"]/following-sibling::XCUIElementTypeTextField"));
	    intField.clear();
	    intField.sendKeys(AstroSky.INTEGER);

	    // Currency field
	    IOSElement currencyField = driver.findElement(MobileBy.iOSClassChain("**/XCUIElementTypeOther[`label == \"Currency ​\"`]"));
	    currencyField.click();

	    // wait for list of currencies to load	    
	    wait.until(
	    		ExpectedConditions.presenceOfElementLocated(
	    				MobileBy.xpath("//XCUIElementTypeOther[@name=\"Currency\"]/XCUIElementTypeOther[3]")));
	    // choose the second value: Euro
	    driver.findElement(MobileBy.AccessibilityId("€")).click();

	    // Multiple currency field
	    WebElement multiCurrField = wait.until(ExpectedConditions.elementToBeClickable(
	    		MobileBy.iOSClassChain("**/XCUIElementTypeOther[`label == \"Currencies ​\"`]")));
	    multiCurrField.click();
	    // wait for list of currencies to load	    
	    wait.until(
	    		ExpectedConditions.presenceOfElementLocated(
	    				MobileBy.xpath("//XCUIElementTypeOther[@name=\"Currencies\"]/XCUIElementTypeOther[3]")));
	    // choose $ only as I can't figure out how to exit the dropdown if Euro is chosen. Strange, but it works with dollar.
	    driver.findElement(MobileBy.AccessibilityId("$")).click();
	    
	    // click out of the dropdown
	    driver.findElement(MobileBy.iOSClassChain(
	    		"**/XCUIElementTypeWindow[1]"))
	                  .click();
	    
	    // tick the checkbox
	    driver.findElement(
	    		MobileBy.iOSClassChain("**/XCUIElementTypeSwitch[`value == \"0\"`]")).click();

	    // radio button
	    // click the fourth one
	    driver.findElement(MobileBy.AccessibilityId("4")).click();
	}



	/**
	 * Validate the lat long values generated by "Take Point" button.
	 */
	@Override
	public void validateLatLong() {
		// We can't actually get the phone's location due to iOS requiring the settings to be always "on", but 
		// Appium's capability for this doesn't actually work. So with iOS, we just make sure we get some numbers. 
		IOSElement lat = driver.findElement(
				MobileBy.xpath("//XCUIElementTypeStaticText[@name=\"Lat:\"]/following-sibling::XCUIElementTypeStaticText"));
		String latVal = lat.getText();
		assertNotNull(latVal);
		assertTrue(!Double.isNaN(Double.parseDouble(latVal)));
		
		IOSElement longi = driver.findElement(
				MobileBy.xpath("//XCUIElementTypeStaticText[@name=\"; Long:\"]/following-sibling::XCUIElementTypeStaticText"));
		String longVal = longi.getText();
		assertNotNull(longVal);
		assertTrue(!Double.isNaN(Double.parseDouble(longVal)));
	}

	@Override
	public String getLatitude() {
		if (latitude == null) {
			latitude = String.valueOf(driver.location().getLatitude());
		}
		return latitude;
	}

	@Override
	public String getLongitude() {
		if (longitude == null) {
		    longitude = String.valueOf(driver.location().getLongitude());
		}
		return longitude;

	}

	/**
	 * Load up new Example B observation form.
	 *
	 */
	@Override
	public void loadNewAstroSkyForm() {
		// Click on "Projects"
		WebElement projects = new WebDriverWait(driver, 10)
				.until(ExpectedConditions.elementToBeClickable(By.xpath("//XCUIElementTypeMenuItem[@name=\"Projects\"]")));
		projects.click();

		// workaround for FAIMS3-263
		try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// Find the '+' button for new observation
		WebElement settings = new WebDriverWait(driver, 10)
				.until(ExpectedConditions.elementToBeClickable(By.xpath("(//XCUIElementTypeButton[@name=\"settings\"])[1]")));
		settings.click();
		WebElement newObservation = driver.findElement(MobileBy.xpath("//XCUIElementTypeMenuItem[@name=\"New Observation\"]"));
		newObservation.click();
		
	}

	public static void tearDown() {
		// The driver.quit statement is required, otherwise the test continues to
		// execute, leading to a timeout.
		driver.quit();
	}

	/**
	 * Validate JSON at the end of the form with input values.
	 * @throws JSONException
	 */
	@Override
	public void validateJSON() throws JSONException, AssertionError {
		// Find JSON
		WebDriverWait wait = new WebDriverWait(driver, 10);

		WebElement json = wait.until(ExpectedConditions.visibilityOf(
				driver.findElement(MobileBy.iOSClassChain(
						"**/XCUIElementTypeOther[`label == \"EDIT, tab panel\"`]/XCUIElementTypeOther[15]/XCUIElementTypeStaticText"))));
		JSONObject jsonObject = new JSONObject(json.getText());
		JSONObject values = jsonObject.getJSONObject("values");
		// Take note of uuid so we can retrieve it later
		this.recordUuid = values.getString("_id");

		JSONObject gps = values.getJSONObject("take-point-field");
		assertEquals(this.latitude, gps.get("latitude").toString());
	    assertEquals(this.longitude, gps.get("longitude").toString());
		assertEquals("Change!", values.get("action-field").toString());
		assertEquals(AstroSky.EMAIL_CHROME, values.get("email-field").toString());
        assertEquals(AstroSky.COLOUR, values.get("str-field").toString());
        assertEquals(AstroSky.UNICODE, values.get("multi-str-field").toString());
        assertEquals(AstroSky.INTEGER, values.get("int-field").toString());
        assertEquals("EUR", values.get("select-field").toString());
        assertEquals("[\"USD\"]", values.get("multi-select-field").toString());
        assertEquals("true", values.get("checkbox-field").toString());
        assertEquals("4", values.get("radio-group-field").toString());
        // no errors
        assertEquals("{}", jsonObject.get("errors").toString());
	}

	@Override
	public void verifyMessage(String message) {
		WebDriverWait wait = new WebDriverWait(driver, 10);
		wait.until(ExpectedConditions.presenceOfElementLocated(
				By.xpath("//div[@class='MuiAlert-message' and @text='" + message + "']")));
	}
}
