// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: export.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_CSV         ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_ZIP         ExportFormat = 2
	ExportFormat_EXPORT_FORMAT_GEOJSON     ExportFormat = 3
	ExportFormat_EXPORT_FORMAT_KML         ExportFormat = 4
	ExportFormat_EXPORT_FORMAT_FULL        ExportFormat = 5
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_CSV",
		2: "EXPORT_FORMAT_ZIP",
		3: "EXPORT_FORMAT_GEOJSON",
		4: "EXPORT_FORMAT_KML",
		5: "EXPORT_FORMAT_FULL",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_CSV":         1,
		"EXPORT_FORMAT_ZIP":         2,
		"EXPORT_FORMAT_GEOJSON":     3,
		"EXPORT_FORMAT_KML":         4,
		"EXPORT_FORMAT_FULL":        5,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_export_proto_enumTypes[0].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_export_proto_enumTypes[0]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

type FullExportConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IncludeTabular     bool                   `protobuf:"varint,1,opt,name=include_tabular,json=includeTabular,proto3" json:"include_tabular,omitempty"`
	IncludeAttachments bool                   `protobuf:"varint,2,opt,name=include_attachments,json=includeAttachments,proto3" json:"include_attachments,omitempty"`
	IncludeGeojson     bool                   `protobuf:"varint,3,opt,name=include_geojson,json=includeGeojson,proto3" json:"include_geojson,omitempty"`
	IncludeKml         bool                   `protobuf:"varint,4,opt,name=include_kml,json=includeKml,proto3" json:"include_kml,omitempty"`
	IncludeMetadata    bool                   `protobuf:"varint,5,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FullExportConfig) Reset() {
	*x = FullExportConfig{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullExportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullExportConfig) ProtoMessage() {}

func (x *FullExportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullExportConfig.ProtoReflect.Descriptor instead.
func (*FullExportConfig) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *FullExportConfig) GetIncludeTabular() bool {
	if x != nil {
		return x.IncludeTabular
	}
	return false
}

func (x *FullExportConfig) GetIncludeAttachments() bool {
	if x != nil {
		return x.IncludeAttachments
	}
	return false
}

func (x *FullExportConfig) GetIncludeGeojson() bool {
	if x != nil {
		return x.IncludeGeojson
	}
	return false
}

func (x *FullExportConfig) GetIncludeKml() bool {
	if x != nil {
		return x.IncludeKml
	}
	return false
}

func (x *FullExportConfig) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=faims.export.v1.ExportFormat" json:"format,omitempty"`
	ViewId        string                 `protobuf:"bytes,3,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullConfig    *FullExportConfig      `protobuf:"bytes,5,opt,name=full_config,json=fullConfig,proto3" json:"full_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ExportRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportRequest) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

func (x *ExportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExportRequest) GetFullConfig() *FullExportConfig {
	if x != nil {
		return x.FullConfig
	}
	return nil
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Sequence      uint32                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileChunk) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileChunk) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\x12\x0ffaims.export.v1\"\xe1\x01\n" +
	"\x10FullExportConfig\x12'\n" +
	"\x0finclude_tabular\x18\x01 \x01(\bR\x0eincludeTabular\x12/\n" +
	"\x13include_attachments\x18\x02 \x01(\bR\x12includeAttachments\x12'\n" +
	"\x0finclude_geojson\x18\x03 \x01(\bR\x0eincludeGeojson\x12\x1f\n" +
	"\vinclude_kml\x18\x04 \x01(\bR\n" +
	"includeKml\x12)\n" +
	"\x10include_metadata\x18\x05 \x01(\bR\x0fincludeMetadata\"\xdb\x01\n" +
	"\rExportRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x125\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1d.faims.export.v1.ExportFormatR\x06format\x12\x17\n" +
	"\aview_id\x18\x03 \x01(\tR\x06viewId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12B\n" +
	"\vfull_config\x18\x05 \x01(\v2!.faims.export.v1.FullExportConfigR\n" +
	"fullConfig\"\x99\x01\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x04R\ttotalSize\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\rR\bsequence*\xa5\x01\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_CSV\x10\x01\x12\x15\n" +
	"\x11EXPORT_FORMAT_ZIP\x10\x02\x12\x19\n" +
	"\x15EXPORT_FORMAT_GEOJSON\x10\x03\x12\x15\n" +
	"\x11EXPORT_FORMAT_KML\x10\x04\x12\x16\n" +
	"\x12EXPORT_FORMAT_FULL\x10\x052Y\n" +
	"\rExportService\x12H\n" +
	"\x06Export\x12\x1e.faims.export.v1.ExportRequest\x1a\x1a.faims.export.v1.FileChunk\"\x000\x01B7Z5github.com/faims/faims3/export-service/internal/pb;pbb\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_export_proto_goTypes = []any{
	(ExportFormat)(0),        // 0: faims.export.v1.ExportFormat
	(*FullExportConfig)(nil), // 1: faims.export.v1.FullExportConfig
	(*ExportRequest)(nil),    // 2: faims.export.v1.ExportRequest
	(*FileChunk)(nil),        // 3: faims.export.v1.FileChunk
}
var file_export_proto_depIdxs = []int32{
	0, // 0: faims.export.v1.ExportRequest.format:type_name -> faims.export.v1.ExportFormat
	1, // 1: faims.export.v1.ExportRequest.full_config:type_name -> faims.export.v1.FullExportConfig
	2, // 2: faims.export.v1.ExportService.Export:input_type -> faims.export.v1.ExportRequest
	3, // 3: faims.export.v1.ExportService.Export:output_type -> faims.export.v1.FileChunk
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		EnumInfos:         file_export_proto_enumTypes,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
