name: "Check License Lines"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: License Checker
        uses: kt3k/license_checker@v1.0.6
