name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2