### Login (Happy path)

POST http://localhost:8080/web/login/local
content-type: application/json

{
    "username": "admin",
    "password": "aSecretPasswordThatCantBeGuessed"
}

### Login (Wrong password)

POST http://localhost:8080/web/login/local
content-type: application/json

{
    "username": "admin",
    "password": "wrongPassword"
}

### Signup (User already exists)

POST http://localhost:8080/web/signup/local
content-type: application/json

{
    "email": "admin",
    "name": "Admin",
    "password": "aSecretPasswordThatCantBeGuessed"
}

### Signup (Happy path)

POST http://localhost:8080/web/signup/local
content-type: application/json

{
    "email": "admin77",
    "name": "Admin User 2",
    "password": "aSecretPasswordThatCantBeGuessed"
}

### Logout

POST http://localhost:8080/web/logout
content-type: application/json

### Get notebooks

GET http://localhost:8080/api/notebooks
content-type: application/json

### Get templates

GET http://localhost:8080/api/templates
content-type: application/json

### New survey from template

POST http://localhost:8080/api/notebooks
content-type: application/json

{
    "template_id": "1736225044552-csiro-rapid-impact-survey",
    "name": "Test template from survey"
}

### Create new template

POST http://localhost:8080/api/templates
content-type: application/json


### Update a template

PUT http://localhost:8080/api/templates/1736918912018-template-2
content-type: application/json


### Get current user
GET http://localhost:8080/api/users/current
content-type: application/json