require_relative '../../../node_modules/.pnpm/@capacitor+ios@7.6.6_@capacitor+core@7.6.6/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.5'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@7.6.6_@capacitor+core@7.6.6/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@7.6.6_@capacitor+core@7.6.6/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityExif', :path => '../../../node_modules/.pnpm/@capacitor-community+exif@7.0.0_@capacitor+core@7.6.6/node_modules/@capacitor-community/exif'
  pod 'CapacitorMlkitBarcodeScanning', :path => '../../../node_modules/.pnpm/@capacitor-mlkit+barcode-scanning@7.5.0_@capacitor+core@7.6.6/node_modules/@capacitor-mlkit/barcode-scanning'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@7.1.2_@capacitor+core@7.6.6/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../node_modules/.pnpm/@capacitor+app-launcher@7.0.4_@capacitor+core@7.6.6/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBrowser', :path => '../../../node_modules/.pnpm/@capacitor+browser@7.0.5_@capacitor+core@7.6.6/node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../../../node_modules/.pnpm/@capacitor+camera@7.0.5_@capacitor+core@7.6.6/node_modules/@capacitor/camera'
  pod 'CapacitorDevice', :path => '../../../node_modules/.pnpm/@capacitor+device@7.0.5_@capacitor+core@7.6.6/node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/.pnpm/@capacitor+filesystem@7.1.8_@capacitor+core@7.6.6/node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../../node_modules/.pnpm/@capacitor+geolocation@7.1.8_@capacitor+core@7.6.6/node_modules/@capacitor/geolocation'
  pod 'CapacitorShare', :path => '../../../node_modules/.pnpm/@capacitor+share@7.0.4_@capacitor+core@7.6.6/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/.pnpm/@capacitor+status-bar@7.0.6_@capacitor+core@7.6.6/node_modules/@capacitor/status-bar'
  pod 'CapgoCapacitorAudioRecorder', :path => '../../../node_modules/.pnpm/@capgo+capacitor-audio-recorder@7.1.10_@capacitor+core@7.6.6/node_modules/@capgo/capacitor-audio-recorder'
  pod 'CapgoCapacitorSpeechRecognition', :path => '../../../node_modules/.pnpm/@capgo+capacitor-speech-recognition@8.1.3_@capacitor+core@7.6.6/node_modules/@capgo/capacitor-speech-recognition'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end


post_install do |installer|
  assertDeploymentTarget(installer)
end
