services:
  couchdb:
    image: couchdb:3@sha256:d341311cf03840dfb96a7c1bcf7ef5b6a6a4d2ac53e01e7a5095329cbe8cd37c
    volumes: 
      - type: volume
        source: couchdb-data
        target: /opt/couchdb/data
    ports:
      - "0.0.0.0:5984:5984"     
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=aSecretPasswordThatCantBeGuessed
    networks:
      - conductor-local-dev
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    networks:
      - conductor-local-dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
networks:
  conductor-local-dev: {}
volumes:
  couchdb-data:
