import {v4 as uuidv4} from 'uuid';

export function related_records() {
  return [
    {
      record_id: uuidv4(),
      hrid: 'CBC123',
      type: 'Parent record',
      route: 'parent_route',
      field_id: uuidv4(),
      field_label: 'cup',
      section: 'section A',
      relation_type_vocabPair: ['is parent', 'is child of'],
    },
    {
      record_id: uuidv4(),
      hrid: 'CBC12345',
      type: 'Container',
      route: 'parent_route',
      field_id: uuidv4(),
      field_label: 'box',
      section: 'section B',
      relation_type_vocabPair: ['is related to', 'is related to'],
    },
    {
      record_id: uuidv4(),
      hrid: 'CBD13423',
      type: 'Container',
      route: 'parent_route',
      field_id: uuidv4(),
      field_label: 'box',
      section: 'Section C',
      relation_type_vocabPair: ['is contained by', 'contains'],
    },
  ];
}
export function related_links_from_fields(
  record_id: string,
  hrid: string,
  record_type: string
) {
  return [
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'section B',
      field_id: uuidv4(),
      field_label: 'box',
      relation_type_vocabPair: ['is related to', 'is related to'],
      link: {
        record_id: uuidv4(),
        hrid: 'Mundi-V3.4',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 2',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['is above', 'is below'],
      link: {
        record_id: uuidv4(),
        hrid: 'Mundi-V33.4',
        type: 'Ice',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 2',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['is above', 'is below'],
      link: {
        record_id: uuidv4(),
        hrid: 'Mundi-V33.43',
        type: 'Ice',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 2',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['has child', 'is parent of'],
      link: {
        record_id: uuidv4(),
        hrid: 'TV33.43',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 1',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['has child', 'is parent of'],
      link: {
        record_id: uuidv4(),
        hrid: 'TV33.43',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
  ];
}
export function field_level_links(
  record_id: string,
  hrid: string,
  record_type: string
) {
  return [
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 1',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['has child', 'is parent of'],
      link: {
        record_id: uuidv4(),
        hrid: 'TV33.43',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 1',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['has child', 'is parent of'],
      link: {
        record_id: uuidv4(),
        hrid: 'MP24.43',
        type: 'Ice',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 1',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['has child', 'is parent of'],
      link: {
        record_id: uuidv4(),
        hrid: 'PL87.87',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
    {
      record_id: record_id,
      hrid: hrid,
      type: record_type,
      route: 'route',
      section: 'Core 1',
      field_id: uuidv4(),
      field_label: 'Field EH',
      relation_type_vocabPair: ['is related to', 'is related to'],
      link: {
        record_id: uuidv4(),
        hrid: 'TR23.9',
        type: 'Water',
        route: 'linked record route',
        lastUpdatedBy: '10/12/2020 11:09am by John Smith',
      },
    },
  ];
}
