/*
 * Copyright 2021, 2022 Macquarie University
 *
 * Licensed under the Apache License Version 2.0 (the, "License");
 * you may not use, this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND either express or implied.
 * See, the License, for the specific language governing permissions and
 * limitations under the License.
 *
 * Filename: AndroidTest.java
 * Description:
 *   TODO
 */

package org.fedarch.faims3.android;

import static org.junit.Assert.assertEquals;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.List;

import org.fedarch.faims3.AstroSky;
import org.fedarch.faims3.E2ETest;
import org.fedarch.faims3.TestUtils;
import org.json.JSONException;
import org.json.JSONObject;
import org.openqa.selenium.By;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.appium.java_client.MobileBy;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.android.nativekey.AndroidKey;
import io.appium.java_client.android.nativekey.KeyEvent;
import io.appium.java_client.remote.AndroidMobileCapabilityType;

public class AndroidTest implements E2ETest {
	protected static AndroidDriver<AndroidElement> driver;

	private static boolean isLocal;

	// Save latitude generated by GPS button for the JSON check later
	protected String latitude;

	// Save long generated by GPS button for the JSON check later
	protected String longitude;

	// Newly created observation form's id
	protected String recordUuid;

	/**
	 * Setup the AndroidDriver based on parameter.
	 * @param localTest If true, then we'll set up a local connection. Otherwise we'll set up a browserstack one.
	 * @param testDesc Test description for browserstack
	 * @return an AndroidDriver instance
	 * @throws MalformedURLException
	 */
	public static void setup(boolean localTest, String testDesc) throws MalformedURLException {
		DesiredCapabilities caps = new DesiredCapabilities();
		// allow location services
	    caps.setCapability(AndroidMobileCapabilityType.GPS_ENABLED, "true");
	    // allow everything else so we don't get permission popups
	    caps.setCapability(AndroidMobileCapabilityType.AUTO_GRANT_PERMISSIONS, "true");
	    // Use UIAutomator2 for devices higher than 7
	    caps.setCapability("automationName", "UiAutomator2");
		if (localTest) {
			localConnectionSetup(caps);
			isLocal = true;
		} else {
		    browserstackSetup(caps, testDesc);
		    isLocal = false;
		}
	}

	/**
	 * Localhost setup for Rini's machine.
	 * @throws MalformedURLException
	 */
	public static void localConnectionSetup(DesiredCapabilities caps) throws MalformedURLException {
	    caps.setCapability("platformName", "Android");
	    caps.setCapability("platformVersion", "10.0");
	    caps.setCapability("deviceName", "Android Emulator");
	    caps.setCapability("adbExecTimeout", "1200000");
	    caps.setCapability("app", "C:\\github\\FAIMS3\\android\\app\\build\\outputs\\apk\\debug\\app-debug.apk");

	    driver = new AndroidDriver<AndroidElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
	}

	/**
	 * Browserstack setup for the test
	 * @param testDescription Test scenario. Link to JIRA if possible.
	 * @throws MalformedURLException
	 */
	public static void browserstackSetup(DesiredCapabilities caps, String testDescription) throws MalformedURLException {
	    caps.setCapability("project", "FAIMS3 - Android Tests");
	    caps.setCapability("build", "Alpha");
	    caps.setCapability("name", testDescription.concat(" : ").concat(TestUtils.getCommitMessage()));

	    // Specify device and os_version for testing
	    caps.setCapability("device", "Google Pixel 3");
	    caps.setCapability("os_version", "10.0");
	    // Latest Appium browserstack version with correct geolocation
	    caps.setCapability("browserstack.appium_version", "1.21.0");

	    turnOnBrowserstackLogs(caps);

	    caps.setCapability("app", System.getenv("app_url"));
	    caps.setCapability("browserstack.user", System.getenv("BROWSERSTACK_USERNAME"));
	    caps.setCapability("browserstack.key", System.getenv("BROWSERSTACK_ACCESS_KEY"));

	    driver = new AndroidDriver<AndroidElement>(
	            new URL("http://hub.browserstack.com/wd/hub"), caps);

	}

	/**
	 * Optional logging options for browserstack
	 * @param caps
	 * @return
	 */
	public static void turnOnBrowserstackLogs(DesiredCapabilities caps) {
	    // Log settings to debug
	    caps.setCapability("browserstack.console", "verbose");
	    HashMap networkLogsOptions = new HashMap<>();
	    networkLogsOptions.put("captureContent", Boolean.TRUE);
	    // turn on network logs
	    caps.setCapability("browserstack.networkLogs", "true");
	    caps.setCapability("browserstack.networkLogsOptions", networkLogsOptions);
	}

	/**
	 * True if this is connected to Browserstack.
	 * @return
	 */
	@Override
	public boolean isUsingBrowserstack() {
		return !isLocal;
	}

	/**
	 * Load up new test Observation form
	 */
	@Override
	public void loadNewAstroSkyForm() {
		WebDriverWait wait = new WebDriverWait(driver, 20);
		// Click on "Projects"
		AndroidElement projects = (AndroidElement) wait.until(ExpectedConditions
				.elementToBeClickable(MobileBy.xpath("//android.view.MenuItem[contains(@text, 'Projects')]")));
		projects.click();

		// Get the right project
		AndroidElement AstroSky = (AndroidElement) wait.until(ExpectedConditions
				.presenceOfElementLocated(MobileBy.xpath("//*[contains(@text, 'Astrosky')]")));

		// workaround for FAIMS3-263
		try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// Find the '+' button
		AndroidElement menuButton = driver.findElement(
				MobileBy.xpath("//*[contains(@text, 'Astrosky')]/../android.view.View[3]/android.widget.Button"));
		menuButton.click();
		AndroidElement newButton = (AndroidElement) wait.until(ExpectedConditions.visibilityOfElementLocated(
				By.xpath("//*[contains(@text, 'New Observation')]")));
		newButton.click();
	}

	/**
	 * Fill out all fields in test AsTRoSkY form with valid values.
	 */
	@Override
	public void fillOutFormWithValidFields() {
		WebDriverWait wait = new WebDriverWait(driver, 10);
		//Press the Take Point Button.
		AndroidElement gpsPoint = (AndroidElement) wait.until(
		        ExpectedConditions.elementToBeClickable(MobileBy.xpath("//*[@text='TAKE POINT']")));
		gpsPoint.click();

		//Observe your longitude and latitude output rendered beside the button, and in the developer side-panel as a JSON object
		wait.until(
		        ExpectedConditions.visibilityOfElementLocated(MobileBy.xpath("//*[@text='Lat: ']")));
		validateLatLong();

		//Press the Action button, note that the JSON debug view now shows Change! rather than hello
		AndroidElement action = driver.findElement(MobileBy.xpath("//*[@text='ACTION!']"));
		action.click();

		// Finish the observation
	    // Email field
	    AndroidElement emailField = driver.findElement(MobileBy.xpath("//*[@resource-id='email-field']"));
	    emailField.sendKeys(AstroSky.EMAIL_ANDROID);

	    // Colour field
	    AndroidElement strField = driver.findElement(MobileBy.xpath("//*[@resource-id='str-field']"));
	    strField.sendKeys(AstroSky.COLOUR);

	    TestUtils.scrollToResourceId(driver, "multi-str-field");

	    // Text area - test unicode
	    AndroidElement textField = driver.findElement(MobileBy.xpath("//*[@resource-id='multi-str-field']"));
	    textField.sendKeys(AstroSky.UNICODE);

	    AndroidElement intField = driver.findElement(By.xpath("//*[@resource-id='int-field']"));
	    intField.click();
	    driver.pressKey(new KeyEvent(AndroidKey.DEL));
	    driver.pressKey(new KeyEvent(AndroidKey.DIGIT_1));
	    driver.pressKey(new KeyEvent(AndroidKey.DIGIT_6));
	    driver.pressKey(new KeyEvent(AndroidKey.ENTER));

	    // Currency field
	    AndroidElement currencyField = driver.findElement(MobileBy.xpath("//*[@resource-id='select-field']"));
	    currencyField.click();

	    // wait for list of currencies to load
	    AndroidElement currencyList = (AndroidElement) wait.until(
	    		ExpectedConditions.presenceOfElementLocated(MobileBy.className("android.widget.ListView")));
	    // choose the second value: Euro
	    try {
	        currencyList.findElements(MobileBy.className("android.view.View")).get(1).click();
	    } catch(StaleElementReferenceException e) {
	    	// sometimes this happens.. try again
	    	currencyList.findElements(MobileBy.className("android.view.View")).get(1).click();
        }
	    // Multiple currency field
	    AndroidElement multiCurrField = (AndroidElement) wait.until(
	            ExpectedConditions.elementToBeClickable(
	            		MobileBy.xpath("//*[@resource-id='multi-select-field']")));
	    multiCurrField.click();
	    // wait for the spinner overlay to disappear so we can see everything on the list
	    wait.until(ExpectedConditions.invisibilityOf(multiCurrField));
	    // choose first, second: $, Euro
	    List<WebElement> currencies = wait.until(ExpectedConditions.visibilityOfNestedElementsLocatedBy(
	    		MobileBy.xpath("//android.view.View/android.widget.ListView"),
	    		MobileBy.xpath("//android.view.View")));
	    currencies.get(0).click();
	    currencies.get(1).click();

	    // click out of the dropdown
	    driver.pressKey(new KeyEvent(AndroidKey.ESCAPE));

	    TestUtils.scrollDown(driver);

	    // tick the checkbox
	    AndroidElement checkbox = (AndroidElement) wait.until(
	    		ExpectedConditions.visibilityOfElementLocated(MobileBy.xpath("//*[@resource-id='checkbox-field']")));
	    checkbox.click();

	    // radio button
	    AndroidElement radioButton = (AndroidElement) wait.until(ExpectedConditions.visibilityOfElementLocated(
	    		MobileBy.xpath("//*[@resource-id='radio-group-field']/android.widget.RadioButton[@text='4']")));
	    // click the fourth one
	    radioButton.click();
	}

	/**
	 * Validate the lat long values generated by "Take Point" button.
	 */
	@Override
	public void validateLatLong() {
		//in Android 10, the element class name is actually android.widget.TextView
		//but otherwise it's android.view.View
		//ideally there should be an id so it's nice and easy, but we work with what we've got
		// so we have to work out the class name and get the siblings
		String className = driver.findElement(By.xpath("//*[@text='Lat: ']")).getAttribute("className");
		AndroidElement lat = driver.findElement(By.xpath("//*[@text='Lat: ']/../" + className + "[2]"));
		assertEquals(getLatitude(), lat.getText());
		AndroidElement longi = driver.findElement(By.xpath("//*[@text='Lat: ']/../" + className + "[4]"));
		assertEquals(getLongitude(), longi.getText());
	}

	@Override
	public String getLatitude() {
		if (latitude == null) {
			latitude = String.valueOf(driver.location().getLatitude());
		}
		return latitude;
	}

	@Override
	public String getLongitude() {
		if (longitude == null) {
		    longitude = String.valueOf(driver.location().getLongitude());
		}
		return longitude;

	}

	/**
	 * Validate JSON at the end of the form with input values.
	 * @return True if JSON is valid, false otherwise.
	 * @throws JSONException
	 */
	@Override
	public void validateJSON() throws JSONException, AssertionError {
		// Find JSON
		WebDriverWait wait = new WebDriverWait(driver, 10);
		WebElement json = wait.until(ExpectedConditions.visibilityOf(
				driver.findElement(MobileBy.xpath("//*[@text='DEVELOPER TOOL: FORM STATE']/following-sibling::android.view.View/android.view.View"))));
		JSONObject jsonObject = new JSONObject(json.getText());
		JSONObject values = jsonObject.getJSONObject("values");

		// Take note of the UUID for other tests
		this.recordUuid = values.getString("_id");

		JSONObject gps = values.getJSONObject("take-point-field");
		assertEquals(this.latitude, gps.get("latitude").toString());
	    assertEquals(this.longitude, gps.get("longitude").toString());
		assertEquals("Change!", values.get("action-field").toString());
		assertEquals(AstroSky.EMAIL_ANDROID, values.get("email-field").toString());
        assertEquals(AstroSky.COLOUR, values.get("str-field").toString());
        assertEquals(AstroSky.UNICODE, values.get("multi-str-field").toString());
        assertEquals(AstroSky.INTEGER, values.get("int-field").toString());
        assertEquals("EUR", values.get("select-field").toString());
        assertEquals("[\"USD\",\"EUR\"]", values.get("multi-select-field").toString());
        // FIXME: seems like an appium bug. The values below aren't updating despite us waiting and reretrieving them
        // Our attempt as below:
		// wait for JSON to be updated by checking that touched has been updated for the last field
		//int tries = 0;
		//while (tries < 3 && !jsonObject.getJSONObject("touched").has("checkbox-field")) {
		//	try {
		//		Thread.sleep(5000);
		//	} catch (InterruptedException e) {
		//		// TODO Auto-generated catch block
		//		e.printStackTrace();
		//	}
		//	json = driver.findElement(MobileBy.xpath(
		//			"//*[@text='DEVELOPER TOOL: FORM STATE']/following-sibling::android.view.View/android.view.View"));
		//	jsonObject = new JSONObject(json.getText());
		//	tries++;
		//}
        //assertEquals("true", values.get("checkbox-field").toString());
        //assertEquals("4", values.get("radio-group-field").toString());
        // no errors
        //assertEquals("{}", jsonObject.get("errors").toString());

	}

	public static void tearDown() {
		// The driver.quit statement is required, otherwise the test continues to
		// execute, leading to a timeout.
		driver.quit();
	}

	@Override
	public void verifyMessage(String message) {
		WebDriverWait wait = new WebDriverWait(driver, 10);
		wait.until(ExpectedConditions.visibilityOfElementLocated(
				MobileBy.xpath("//*[@text='" + message + "']")));
	}
}
