#!/bin/sh

export REACT_APP_DIRECTORY_HOST=10.80.11.44
export REACT_APP_DIRECTORY_PORT=5984
export REACT_APP_USE_HTTPS=false
export REACT_APP_USE_REAL_DATA=false
export REACT_APP_PRODUCTION_BUILD=false
