name: Deploy to Google Play For Production

on:
  workflow_dispatch:

jobs:
  node-deb-gh-build-play:
    uses: ./.github/workflows/common-android-build.yml
    with:
      android_deploy_track: production
      enable_bugsnag_sourcemaps: true
      serverprefix: fieldmark
    secrets: inherit
