name: Deploy to Apple App Store Production, Manual

on:
  workflow_dispatch:

jobs:
  ios-deploy:
    name: Deploying to Production
    runs-on: macOS-latest
    steps:
      # note not using Turbo build as it caused a problem with missing assets
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install jq
        run: |
          brew update
          brew install jq
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "app_version=$(jq -r '.version' app/package.json)" >> "$GITHUB_ENV"
      - name: Create version string
        shell: bash
        run: |
          echo "version_string=v${{env.app_version}}-ios-#${{env.sha_short}}" >> "$GITHUB_ENV"

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
          working-directory: app/ios/App
      - run: |
          cd app/ios/App
          bundle install
          bundle exec fastlane install_plugins
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Building webapp
        run: |
          export platform="github-actions-ios"
          export serverprefix="fieldmark"
          export VITE_CLUSTER_ADMIN_GROUP_NAME=cluster-admin
          export VITE_COMMIT_VERSION=${{env.version_string}}
          export VITE_SHOW_WIPE=true
          export VITE_SHOW_POUCHDB_BROWSER=false
          export VITE_POUCH_BATCH_SIZE=${{vars.POUCH_BATCH_SIZE}}
          export VITE_CONDUCTOR_URL=${{vars.PRODUCTION_CONDUCTOR_URL}}
          export VITE_TAG=prodIOS
          export VITE_NOTEBOOK_LIST_TYPE=${{vars.NOTEBOOK_LIST_TYPE}}
          export VITE_NOTEBOOK_NAME=${{vars.NOTEBOOK_NAME}}
          export VITE_THEME=${{vars.THEME}}
          export VITE_BUGSNAG_KEY=${{secrets.BUGSNAG_KEY}}
          export VITE_APP_ID=${{vars.APP_ID}}
          export VITE_APP_NAME="${{vars.APP_NAME}}"
          export VITE_SHOW_RECORD_SUMMARY_COUNTS="${{vars.VITE_SHOW_RECORD_SUMMARY_COUNTS}}"
          export VITE_APPLE_BUNDLE_IDENTIFIER="${{vars.APPLE_BUNDLE_IDENTIFIER}}"
          export VITE_APP_STORE_CONNECT_TEAM_ID="${{secrets.APP_STORE_CONNECT_TEAM_ID}}"
          export VITE_APP_PRIVACY_POLICY_URL=${{vars.APP_PRIVACY_POLICY_URL}}
          export VITE_SUPPORT_EMAIL=${{vars.SUPPORT_EMAIL}}
          export VITE_APP_CONTACT_URL=${{vars.APP_CONTACT_URL}}


          export VITE_ENABLE_RECORD_FILTERS=${{vars.ENABLE_RECORD_FILTERS}}
          export VITE_HEADING_APP_NAME="${{vars.HEADING_APP_NAME}}"
          export VITE_MAP_SOURCE=${{vars.MAP_SOURCE}}
          export VITE_MAP_SOURCE_KEY="${{secrets.MAP_SOURCE_KEY}}"
          # could make these configurable but enable by default for now
          export VITE_OFFLINE_MAPS=true
          export VITE_MAP_STYLE=basic

          pnpm install --frozen-lockfile --python=python3.10
          # we install these here because of a bug in npm with platform specific
          # dependencies
          pnpm install @rollup/rollup-darwin-arm64 @swc/core-darwin-arm64
          pnpm --filter=@faims3/app run configIOSbuild 
          pnpm run build          
          # upload sourcemaps to bugsnag (script is conditional on BUGSNAG_KEY and uses VITE_APPLE_BUNDLE_IDENTIFIER on IOS)
          cd app
          ./bin/bugsnag-sourcemaps.sh IOS
      - name: Update IOS Build
        run: |
          cd app
          npx cap update ios
          npx cap sync --deployment ios
          cd ios/App; pod install
      - name: Set up XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.3
      - name: Deploy iOS app to production with Fastlane
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: production
          subdirectory: 'app/ios/App'
          bundle-install-path: '$HOME/vendor/bundle'
          verbose: false
        env:
          VITE_APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ vars.DEVELOPER_APP_ID }}'
          VITE_APPLE_BUNDLE_IDENTIFIER: '${{ vars.APPLE_BUNDLE_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          MATCH_GIT_URL: '${{ vars.MATCH_GIT_URL }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
          BROWSERSTACK_USERNAME: '${{secrets.BROWSERSTACK_USERNAME}}'
          BROWSERSTACK_ACCESS_KEY: '${{secrets.BROWSERSTACK_ACCESS_KEY}}'
