name: Deploy to Apple App Store Production, Manual

on:
  workflow_dispatch:

jobs:
  ios-deploy:
    name: Deploying to Production
    uses: ./.github/workflows/common-ios-build.yml
    with:
      fastlane_lane: production
      fastlane_step_name: Deploy iOS app to production with Fastlane
      enable_bugsnag_sourcemaps: true
    secrets: inherit
